// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5yYDUHb9UmWIV01Ew_cRoAv7Q6lpbKo',
    appId: '1:901787842217:web:4e35e76b744893425e1bb8',
    messagingSenderId: '901787842217',
    projectId: 'ngandika-app',
    authDomain: 'ngandika-app.firebaseapp.com',
    storageBucket: 'ngandika-app.appspot.com',
    measurementId: 'G-ZP4D7LMBGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJcvLoS1o3pgLKTeIyW1BUYzEPNQJwtac',
    appId: '1:901787842217:android:22d5bc2cc411b3095e1bb8',
    messagingSenderId: '901787842217',
    projectId: 'ngandika-app',
    storageBucket: 'ngandika-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEYEBlkQqVjCcWpcZ1jtdxpAcVs8y7nY',
    appId: '1:901787842217:ios:513452fa049ca9265e1bb8',
    messagingSenderId: '901787842217',
    projectId: 'ngandika-app',
    storageBucket: 'ngandika-app.appspot.com',
    androidClientId:
        '901787842217-gs4u9cef9i2odcvt5g4fbsb7svk7b437.apps.googleusercontent.com',
    iosClientId:
        '901787842217-iop5sfa17a7jul44bb5s7ibbveih60cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngandikaApp',
  );
}
